export const ActionTypes = {
  UPDATE_DISHES: "UPDATE_DISHES",
  UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
  UPDATE_INGREDIENTS: "UPDATE_INGREDIENTS",
  FETCH_INGREDIENTS_START: "FETCH_INGREDIENTS_START",
  FETCH_INGREDIENTS_SUCCESS: "FETCH_INGREDIENTS_SUCCESS",
  FETCH_INGREDIENTS_FAIL: "FETCH_INGREDIENTS_FAIL",
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  DESELECT_ITEM: "DESELECT_ITEM",
  SELECT_ITEM: "SELECT_ITEM",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  REMOVE_ITEM: "REMOVE_ITEM"
};
