export const DataTypes = {
  DISHES: "dishes",
  CATEGORIES: "categories",
  INGREDIENTS: "ingredients"
};

export const ActionTypes = {
  DATA_LOAD: "data_load",
  UPDATE_DISHES: "UPDATE_DISHES",
  UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
  UPDATE_INGREDIENTS: "UPDATE_INGREDIENTS",
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  DESELECT_ITEM: "DESELECT_ITEM",
  SELECT_ITEM: "SELECT_ITEM",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM"
};
